import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Socials from '../components/Socials'
import styles from '../styles/Home.module.scss'

const Canvas = dynamic(() => import('../components/Canvas'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Navbar />
        <section className={styles.heading}>
          <Canvas />
          <h1>
            Bonjour, je m'appelle Antonin Barbier.
            <br />
            <span>Je suis développeur front-end.</span>
          </h1>
        </section>
      </main>
      <Socials />
      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
